name: dev_udemy_angelayu
description: A Flutter application for The Complete 2019 Flutter Development Bootcamp with Dart  Created by Angela Yu.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  audioplayers: ^0.13.2
  rflutter_alert: ^1.0.3
  font_awesome_flutter: ^8.5.0

  geolocator: ^5.1.4+2
  http: ^0.12.0+2
  flutter_spinkit: ^4.0.0

  animated_text_kit: ^1.3.1
  firebase_auth: ^0.14.0
  modal_progress_hud: ^0.1.3
  cloud_firestore: ^0.12.9
  #firebase_core: ^0.3.4
  #firebase_auth: ^0.8.4+4
  #cloud_firestore: ^0.9.13+1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/
  fonts:
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf

    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf

    - family: SpartanMB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900
